"""
Generate a 14x28 ANTI-ALIASED grayscale bitmap font from Consolas for MemForge.
Outputs font_data.h with glyph data + codepoint→index lookup.

OLD format (1-bit):  UINT16 g_font_glyphs[GLYPHS][H]   (1 bit per pixel, ~50 B/glyph)
NEW format (8-bit):  UINT8  g_font_glyphs[GLYPHS][H][W] (1 byte alpha per pixel, ~390 B/glyph)

The C-side renderer treats each byte as alpha (0=transparent, 255=opaque text colour)
and blends with the framebuffer background per pixel — gives smooth, AA-rendered
text instead of the previous jagged 1-bit edges.

Coverage:
  - ASCII 0x20-0x7E (95 chars)
  - Cyrillic uppercase А-Я (U+0410-U+042F)
  - Cyrillic lowercase а-я (U+0430-U+044F)
  - Ё (U+0401), ё (U+0451)
  - Punctuation, box-drawing, symbols used in UI
"""
from PIL import Image, ImageDraw, ImageFont

FONT_PATH = "C:/Windows/Fonts/consola.ttf"
# Consolas is a MONOSPACE font — every glyph has the same advance width.
# PT=17 places it in a ~12-px-wide nominal cell within our 14-px renderer
# cell, leaving 2 px of safe edge for the AA halo. Going lower (PT=16) makes
# Cyrillic look anaemic; higher (PT=18) clips wide glyphs like "ш" / "щ".
PT = 17
W, H = 14, 28

codepoints = []
# ASCII printable
for cp in range(0x20, 0x7F):
    codepoints.append(cp)
# Cyrillic uppercase
for cp in range(0x0410, 0x0430):
    codepoints.append(cp)
# Cyrillic lowercase
for cp in range(0x0430, 0x0450):
    codepoints.append(cp)
# Yo
codepoints.append(0x0401)
codepoints.append(0x0451)
# Box drawing + bullets + Latin-1 supplement chars actually used in UI
codepoints.extend([
    0x00B0,  # ° (degree)
    0x00B1,  # ± (plus-minus)
    0x00B7,  # · (middle dot — separator in live metrics)
    0x00D7,  # × (multiplication sign)
    0x2014,  # — (em dash)
    0x2026,  # … (horizontal ellipsis — truncated text)
    0x2192,  # → (right arrow)
    0x2500,  # ─
    0x2502,  # │
    0x250C,  # ┌
    0x2510,  # ┐
    0x2514,  # └
    0x2518,  # ┘
    0x251C,  # ├
    0x2524,  # ┤
    0x252C,  # ┬
    0x2534,  # ┴
    0x253C,  # ┼
    0x25CF,  # ●
    0x25CB,  # ○
    0x26A0,  # ⚠
    0x2713,  # ✓
    0x2717,  # ✗
])

font = ImageFont.truetype(FONT_PATH, PT)

def render_glyph(cp):
    """Render glyph as 8-bit grayscale: 0 = bg, 255 = full text colour,
    intermediate = AA edge alpha. PIL's 'L' mode with ClearType-style font
    rendering already produces the soft halo we want; we just keep the
    grayscale value as-is instead of thresholding."""
    img = Image.new('L', (W, H), 0)
    draw = ImageDraw.Draw(img)
    ch = chr(cp)
    draw.text((0, -1), ch, fill=255, font=font)
    rows = []
    for y in range(H):
        row = []
        for x in range(W):
            row.append(img.getpixel((x, y)))
        rows.append(row)
    return rows

print(f"Generating {len(codepoints)} AA glyphs at {W}x{H}px from {FONT_PATH}...")

lines = []
lines.append("/* AUTO-GENERATED by gen_font.py — do not edit. */")
lines.append("/* ANTI-ALIASED 8-bit grayscale: each byte = alpha (0..255).")
lines.append("   The renderer blends pixel = bg + (fg - bg) * alpha / 255. */")
lines.append("#ifndef MEMFORGE_FONT_DATA_H")
lines.append("#define MEMFORGE_FONT_DATA_H")
lines.append("")
lines.append(f"#define FONT_W {W}")
lines.append(f"#define FONT_H {H}")
lines.append(f"#define FONT_GLYPHS {len(codepoints)}")
lines.append("")
lines.append(f"/* Each glyph: {H} rows × {W} columns of UINT8 alpha (0..255). */")
lines.append(f"static const UINT8 g_font_glyphs[FONT_GLYPHS][FONT_H][FONT_W] = {{")

for cp in codepoints:
    rows = render_glyph(cp)
    try:
        comment = f"/* U+{cp:04X} '{chr(cp)}' */"
    except Exception:
        comment = f"/* U+{cp:04X} */"
    lines.append(f"  {{  {comment}")
    for r in rows:
        rowstr = ", ".join(f"0x{v:02X}" for v in r)
        lines.append(f"    {{ {rowstr} }},")
    lines.append("  },")

lines.append("};")
lines.append("")
lines.append("/* Codepoint → glyph index. Sorted by cp for binary search. */")
lines.append("typedef struct { UINT16 cp; UINT16 idx; } font_cp_entry_t;")
lines.append("static const font_cp_entry_t g_font_cp_map[FONT_GLYPHS] = {")

pairs = sorted([(cp, i) for i, cp in enumerate(codepoints)], key=lambda p: p[0])
for cp, idx in pairs:
    lines.append(f"    {{ 0x{cp:04X}, {idx:3d} }},")

lines.append("};")
lines.append("")
lines.append("#endif")

with open("font_data.h", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

bytes_total = len(codepoints) * H * W
print(f"Wrote font_data.h with {len(codepoints)} grayscale glyphs, "
      f"~{bytes_total} bytes glyph data (was ~{len(codepoints) * H * 2}B as 1-bit).")
